version: 2.1

commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      # Add parameter here   
      workflow_id:
          type: string         
      
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            # Your code here
            echo "<<parameters.workflow_id>>"
            aws s3 rb s3://udapeople-<<parameters.workflow_id>> --force
            aws cloudformation delete-stack --stack-name "udapeople-krajeevs-p03-front-end-<<parameters.workflow_id>>"
            aws cloudformation delete-stack --stack-name "udapeople-krajeevs-p03-back-end-<<parameters.workflow_id>>"

            #exit 1

  revert-migrations:
    description: Revert the last migration if successfully run in the current workflow.
    parameters:
      # Add parameter here  
      workflow_id:
          type: string

    steps:
      - run:
          name: Revert migrations
          # Add when this will run
          when: on_fail
          command: |
            echo "<<parameters.workflow_id>>"
            SUCCESS=`curl -H "token: krajeevs_<<parameters.workflow_id>>" --request GET https://api.memstash.io/values/migration_<<parameters.workflow_id>> `
            
            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
            # SUCCESS = 1
            if(( $SUCCESS==1 )); 
            then
            cd ~/project/backend
            npm install
            #  Add revert code here. You can find this in the Getting Started section.
            npm run migrations:revert
              #exit 1
            fi
            
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            # Your code here
            #echo `pwd`
            #ls -lart
            cd ~/project/frontend
            npm i
            npm run build
            echo "Done-frontend-build"
            #exit 1
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
             # Your code here
             #echo `pwd`
             cd ~/project/backend
             npm i
             npm run build
             echo "Done-backend-build"
             #exit 1
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test-frontend:
    docker:
      # Docker image here
      - image: circleci/node:13.8.0
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          keys: [frontend-build]
      # Your job code here
      - run: npm i
      - run: npm run test             
                      
  test-backend:
    docker:
      # Docker image here
      - image: circleci/node:13.8.0
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          keys: [backend-build]
      # Your job code here
      - run: npm i
      - run: npm run test
            
  scan-frontend:
    docker:
      # Docker image here
      - image: circleci/node:13.8.0
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          keys: [frontend-build]
      # Your job code here
      - run:
          name: Scan front-end
          command: |
            cd frontend
            npm i
            #npm audit --audit-level=critical
            npm audit fix --audit-level=critical --force
          
  scan-backend:
    docker:
      # Docker image here
      - image: circleci/node:13.8.0
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          keys: [backend-build]
      # Your job code here
      - run:
          name: Scan backend-end
          command: |
            cd backend
            npm i
            #npm audit --audit-level=critical
            npm audit fix --audit-level=critical --force
          
  deploy-infrastructure:
    docker:
      # Docker image here that supports AWS CLI
      - image: amazon/aws-cli
    steps:
      # Checkout code from git
      - checkout
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --tags project=udapeople \
               --stack-name "udapeople-krajeevs-p03-back-end-${CIRCLE_WORKFLOW_ID:0:7}" \
               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"

   
      - run:
          name: Ensure front-end infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --tags project=udapeople \
               --stack-name "udapeople-krajeevs-p03-front-end-${CIRCLE_WORKFLOW_ID:0:7}" \
               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
      #- run: aws s3 sync . s3://udapeople-"${CIRCLE_WORKFLOW_ID:0:7}"
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            # Your code here
            echo "[web]" > inventory.txt
            aws ec2 describe-instances --query Reservations[*].Instances[*].[PublicDnsName] --filters Name=tag-value,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} --output text >> inventory.txt
            cp -p inventory.txt ~/project/.circleci/ansible/inventory.txt
            aws ec2 describe-instances --query Reservations[*].Instances[*].[PublicIpAddress] --filters Name=tag-value,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} --output text >> backend_url.txt
            mkdir ~/project/backend/dist
            mkdir ~/project/frontend/dist
            #aws s3 sync . s3://udapeople-"${CIRCLE_WORKFLOW_ID:0:7}"
            
            cat ~/project/.circleci/ansible/inventory.txt
            cat backend_url.txt
            #cat ~/project/backend_url.txt

            yum -y install tar gzip
            #exit 1
      - persist_to_workspace:
          root: ~/
          paths:
            #- project/.circleci/ansible/inventory.txt
            - project/
      # Here's where you will add some code to rollback on failure      
      - destroy-environment: 
          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}

  configure-infrastructure:
    docker:
      # Docker image here that supports Ansible
      - image: python:3.7-alpine3.11
    steps:
      # Checkout code from git
      - checkout
      # Add ssh keys with fingerprint
      - add_ssh_keys:
          fingerprints: ["9b:ef:6f:6e:9c:70:08:e3:52:7a:2d:18:4c:4e:68:4e"]
          
      # attach workspace
      - attach_workspace:
          at: ~/          
          
      - run:
          name: Install dependencies
          command: |
            # Your code here
            apk add --update ansible
            pip install awscli
            #exit 1
      - run:
          name: Configure server
          command: |
            # Your code here
            cat ~/project/.circleci/ansible/inventory.txt
            ansible-playbook ~/project/.circleci/ansible/configure-server.yml -i ~/project/.circleci/ansible/inventory.txt
            #exit 1
      # Here's where you will add some code to rollback on failure      
      - destroy-environment: 
          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
          
  run-migrations:
    docker:
      # Docker image here that supports NodeJS
      - image: circleci/node:13.8.0

    steps:
      # Checkout code from git
      - checkout
      - attach_workspace:
          at: ~/ 
      - run:
          name: Install dependencies
          command: |
            # Your code here
            sudo apt-get update
            sudo apt-get install python3
            sudo apt-get install awscli
            #exit 1
      - run:
          name: Run migrations
          no_output_timeout: 20m
          command: |
            # Your code here
            cd ~/project/backend
            npm i
            #npm run migrations:revert
            #npm run migrations
            mystatus=$( npm run migrations | grep -i "has been executed successfully")
            echo $mystatus >> ~/project/migrations_status.txt
            
      - persist_to_workspace:
          root: ~/
          paths:
            - project/
       
      - run:
          name: Send migration results to memstash
          command: |
            # Your code here
            if [ -z $mystatus ]
            then
            curl -H "Content-Type: text/plain" -H "token: krajeevs_${CIRCLE_WORKFLOW_ID:0:7}" --request PUT --data "0" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
            else
            echo 'Success'
            curl -H "Content-Type: text/plain" -H "token: krajeevs_${CIRCLE_WORKFLOW_ID:0:7}" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
            fi
            
            #curl -H "token: krajeevs_${CIRCLE_WORKFLOW_ID:0:7}" --request GET https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
            # exit 1
     # Here's where you will add some code to rollback on failure      
      - revert-migrations: 
          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
      - destroy-environment: 
          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
          
  deploy-frontend:
    docker:
      # Docker image here that supports AWS CLI
      #- image: amazon/aws-cli
      #- image: python:3.7-alpine3.11
      - image: circleci/node:13.8.0
    steps:
      # Checkout code from git
      - checkout
      #- run: yum -y install tar gzip
      - restore_cache:
          keys: [frontend-build]
      #- attach_workspace:
          #at: ~/ 
      - run:
          name: Install dependencies
          command: |
            # your code here
            sudo apt-get update
            #sudo apt-get install python3
            #sudo apt-get install awscli
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
            unzip awscliv2.zip 
            sudo ./aws/install 


      - run:
          name: Get backend url            
          command: |
            # your code here
            # BACKEND_IP=`cat ~/project/backend_url.txt`
            export BACKEND_IP=$(aws ec2 describe-instances \
              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --output text)
              
            export API_URL="http://${BACKEND_IP}:3030"
            echo "API_URL=$API_URL" >> frontend/.env
            echo "${API_URL}"
      - run:
          name: Deploy frontend objects
          no_output_timeout: 20m
          command: |
            # your code here
            

            
            cd ~/project/frontend
            npm install
            npm run build
            ls -lart
            tar -C dist -czvf dist.tar.gz .
            pwd


            #aws s3 cp dist.tar.gz s3://udapeople-krajeevs-p03/frontend/
            #aws s3 cp dist.tar.gz s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}  
            aws s3 sync dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}
            #aws s3 cp dist/index.html s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}



            
      # Here's where you will add some code to rollback on failure      
      - revert-migrations: 
          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
      - destroy-environment: 
          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
          
  deploy-backend:
    docker:
      # Docker image here that supports Ansible
      - image: python:3.7-alpine3.11
    steps:
      # Checkout code from git
      - checkout
      - restore_cache:
          keys: [backend-build]
      # Add ssh keys with fingerprint
      - add_ssh_keys:
          fingerprints: ["9b:ef:6f:6e:9c:70:08:e3:52:7a:2d:18:4c:4e:68:4e"]
      # attach workspace
      - attach_workspace:
          at: ~/  
      - run:
          name: Install dependencies
          command: |
            # your code here
            apk add --update ansible curl
            pip install awscli
      - run:
          name: Deploy backend
          no_output_timeout: 30m
          command: |
            # your code here
            echo ENVIRONMENT=production >> "backend/.env"
            echo TYPEORM_CONNECTION=postgres >> "backend/.env"
            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> "backend/.env"
            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> "backend/.env"
            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> "backend/.env"
            echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
            echo TYPEORM_PORT=$TYPEORM_PORT >> "backend/.env"
            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"
            
            tar -C backend -czvf artifact.tar.gz .
            cp -p artifact.tar.gz ~/project/backend/artifact.tar.gz
            ls -alrt 
            pwd
            #aws s3 cp artifact.tar.gz s3://udapeople-krajeevs-p03/ 
            cat ~/project/.circleci/ansible/inventory.txt
            ansible-playbook ~/project/.circleci/ansible/deploy-backend.yml -i ~/project/.circleci/ansible/inventory.txt
            #exit 1
      # Here's where you will add some code to rollback on failure  
      - revert-migrations: 
          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
      - destroy-environment: 
          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}


  smoke-test:
    docker:
      # Lightweight Docker image 
      - image: python:3.7-alpine3.11
    steps:
      # Checkout code from git
      - checkout
      - run:
          name: Install dependencies
          command: |
            # your code here
            apk add --update curl
            #apt-get install python3-pip
            pip install awscli
      - attach_workspace:
          at: ~/ 
      - run:
          name: Get backend url
          command: |
            # your code here
            #URL=`cat ~/backend_url.txt`":3030/api/status"
            URL=$(aws ec2 describe-instances --query Reservations[*].Instances[*].[PublicIpAddress] --filters Name=tag-value,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} --output text)
            echo ${URL}>>my_backend_url.txt
      - run:
          name: Backend smoke test.
          command: |
            # your code here
            URL=`cat ~/project/my_backend_url.txt`":3030/api/status"
            echo ${URL}
            if curl -s ${URL} | grep "ok"
            then
            echo "Success"
            return 0
            else
            echo "Not Found"
            return 1
            fi
      - run:
          name: Frontend smoke test.
          command: |
            # your code here
            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-west-2.amazonaws.com"
            echo ${URL}
            if curl -s ${URL} | grep "Welcome"
            then
            return 0
            else
            return 1
            fi
            
      # Here's where you will add some code to rollback on failure  
      - revert-migrations: 
          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
      - destroy-environment: 
          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
          
  cloudfront-update:
    docker:
      # Docker image here that supports AWS CLI
      - image: amazon/aws-cli
    steps:
      # Checkout code from git
      - checkout
      - run:
          name: Install dependencies
          command: |
            # your code here
            yum -y install tar gzip
      - run:
          name: Update cloudfront distribution
          command: |
            # your code here
            export OldWorkflowID=$(aws cloudformation list-exports \
            --query "Exports[?Name=='WorkflowID'].Value" \
            --no-paginate --output text)
            
            echo $OldWorkflowID > oldworkflowid.txt
            cat oldworkflowid.txt
            
            export STACKS=$(aws cloudformation list-stacks \
            --query "StackSummaries[*].StackName" \
            --stack-status-filter CREATE_COMPLETE \
            --no-paginate --output text) 
            
            aws cloudformation deploy \
              --template-file .circleci/files/cloudfront.yml \
              --stack-name mystack-udapeople-krajeevs-p03 \
              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
              --tags project=udapeople
            
            echo $STACKS
            echo $STACKS > stacks.txt
            cat stacks.txt
            
      - persist_to_workspace:
          root: ~/
          paths:
            - project/oldworkflowid.txt
            - project/stacks.txt
      # Here's where you will add some code to rollback on failure  
      - revert-migrations: 
          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
      - destroy-environment: 
          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
  
  cleanup:
    docker:
      # Docker image here
      - image: amazon/aws-cli
    steps:
      # Checkout code from git
      - checkout
      - run: yum -y install tar gzip
      - attach_workspace:
          at: ~/ 
      - run:
          name: Get old stack workflow id and Remove old stacks and files
          command: |
            # your code here
            export OldWorkflowID=`cat oldworkflowid.txt`
            #export STACKS=[] #put the list of stacks here
            export STACKS=$(aws cloudformation list-stacks \
            --query "StackSummaries[*].StackName" \
            --stack-status-filter CREATE_COMPLETE \
            --no-paginate --output text) 

            echo ${STACKS[@]}
            echo "OldWorkflowID is " ${OldWorkflowID}
            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]; then
              # your code here
              aws cloudformation delete-stack --stack-name "udapeople-krajeevs-p03-back-end-${OldWorkflowID}"
              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
              aws cloudformation delete-stack --stack-name "udapeople-krajeevs-p03-front-end-${OldWorkflowID}"
              
            fi

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - deploy-infrastructure:
          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
          filters:
            branches:
              only: [master]
              #only: [test-feature-branch]
      - configure-infrastructure:
          requires: [deploy-infrastructure]
      - run-migrations:
          requires: [configure-infrastructure]
          
      - deploy-frontend:
          requires: [run-migrations]
      - deploy-backend:
          requires: [run-migrations]
          #requires: [deploy-frontend]
          
          
      - smoke-test:
          requires: [deploy-backend, deploy-frontend]
      - cloudfront-update:
          requires: [smoke-test]
      - cleanup:
          requires: [cloudfront-update]
